# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('wipro', ['core'])
    module.source = [
        'model/wipro.cc',
        'model/tau.cc',
        'model/tau_sync.cc',
        'model/tau_to_sync.cc',
        'model/trickle_time.cc',
        'model/SSID_formatter.cc',
        'model/my_timer.cc',
        'model/wifi_scanner.cc',
        'model/wifi_receiver.cc',
        'model/duty_cycle_application.cc',
        'helper/duty_cycle_application_helper.cc',
        'helper/wipro-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('wipro')
    module_test.source = [
        'test/wipro-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'wipro'
    headers.source = [
        'model/wipro.h',
        'model/tau.h',
        'model/tau_sync.h',
        'model/tau_to_sync.h',
        'model/trickle_time.h',
        'model/SSID_formatter.h',
        'model/my_timer.h',
        'model/wifi_scanner.h',
        'model/wifi_receiver.h',
        'model/duty_cycle_application.h',
        'helper/duty_cycle_application_helper.h',
        'helper/wipro-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

